# fly.toml app configuration file generated for gsrv on 2023-08-06T15:55:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gsrv"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
